import type {
  AuthMode,
  BrowserSessionAuditEventPlan,
  BrowserSessionAuthBlockerCode,
  BrowserSessionAuthRuntimeStatus,
} from "./types.js";

export type BrowserSessionAuthPlannerInput = {
  authMode: AuthMode;
  localOnlyMode: boolean;
};

const browserSessionBlockers: readonly BrowserSessionAuthBlockerCode[] = [
  "browser-session-auth-planning-only",
  "browser-session-cookies-not-accepted",
  "browser-session-issuance-inactive",
  "browser-session-csrf-enforcement-inactive",
  "browser-session-cookie-policy-planning-only",
  "browser-session-pairing-login-planning-only",
  "browser-pairing-issuance-inactive",
  "browser-pairing-consumption-inactive",
  "browser-session-lifecycle-inactive",
  "browser-session-logout-inactive",
  "browser-session-revoke-all-inactive",
  "browser-cookie-issuance-inactive",
  "browser-csrf-token-issuance-inactive",
];

const browserSessionAuditEvents: readonly BrowserSessionAuditEventPlan[] = [
  "browser_pairing_issue_attempted",
  "browser_pairing_issue_succeeded",
  "browser_pairing_issue_denied",
  "browser_pairing_consume_attempted",
  "browser_pairing_consume_succeeded",
  "browser_pairing_consume_denied",
  "browser_session_issue_attempted",
  "browser_session_issue_succeeded",
  "browser_session_issue_denied",
  "browser_session_logout_succeeded",
  "browser_session_revoke_all_succeeded",
  "browser_session_denied_invalid",
  "browser_session_denied_expired",
  "browser_session_denied_revoked",
  "browser_csrf_denied",
];

export function planBrowserSessionAuth(
  input: BrowserSessionAuthPlannerInput,
): BrowserSessionAuthRuntimeStatus {
  const pairingBlockers: readonly BrowserSessionAuthBlockerCode[] = [
    "browser-session-pairing-login-planning-only",
    "browser-pairing-issuance-inactive",
    "browser-pairing-consumption-inactive",
    ...(input.authMode !== "protected" ? (["browser-session-auth-planning-only"] as const) : []),
  ];

  return {
    status: "planning-only",
    liveSessionAuth: false,
    acceptsSessionCookies: false,
    sessionIssuance: "inactive",
    csrfEnforcement: "inactive",
    sessionRoutes: "stubbed",
    pairingRoutes: "stubbed",
    csrfEndpoint: "stubbed",
    frontendTokenStorage: false,
    networkExposureSafe: false,
    lifecycleCoordinator: {
      status: "inactive",
      implementation: "in-memory-test-primitive",
      mounted: false,
      wiredIntoAuthorization: false,
      wiredIntoRoutes: false,
      issuesLiveCookies: false,
      acceptsCookies: false,
      enablesBrowserSessions: false,
      usesSanitizedAuditEvents: true,
    },
    cookiePolicy: {
      issuance: "inactive",
      httpOnly: "required",
      sameSite: "planned",
      secure: "required-outside-local-dev",
      devHttpException: "planned-localhost-only",
      path: "planned",
      domain: "omitted",
      setsCookiesToday: false,
      nonLocalHttp: "unsafe",
      policyPrimitives: {
        status: "inactive",
        implementation: "policy-test-primitive",
        wiredIntoAuthorization: false,
        wiredIntoRoutes: false,
        issuesCookies: false,
        acceptsCookies: false,
      },
      headerSanitizer: {
        status: "inactive",
        implementation: "header-redaction-test-primitive",
        wiredIntoAuthorization: false,
        wiredIntoRoutes: false,
        redactsCookieHeaders: true,
        redactsAuthorizationHeaders: true,
        redactsSetCookieHeaders: true,
        redactsCsrfHeaders: true,
      },
    },
    pairing: {
      enabled: false,
      status: "planning-only",
      issueCode: "inactive",
      consumeCode: "inactive",
      preferredFlow: "local-pairing-code-from-authorized-bearer",
      requiresExistingBearerCredential: true,
      requiresLocalOrigin: true,
      requiresStrongerConfirmation: true,
      codesAreShortLived: true,
      codesAreOneTimeUse: true,
      storesRawCodes: false,
      auditRecordsSanitized: true,
      codeStore: {
        status: "inactive",
        implementation: "in-memory-test-primitive",
        wiredIntoAuthorization: false,
        wiredIntoRoutes: false,
      },
      codeVerifier: {
        status: "inactive",
        implementation: "hash-and-constant-time-compare-primitive",
        wiredIntoAuthorization: false,
        wiredIntoRoutes: false,
        storesRawCodes: false,
      },
      blockers: pairingBlockers,
    },
    sessionLifecycle: {
      issuance: "inactive",
      sessionStore: "planned",
      sessionVerifier: "planned",
      sessionRevocation: "planned",
      expiry: "planned",
      logout: "inactive",
      revokeAll: "inactive",
      currentSessionRevocation: "planned",
      allSessionRevocation: "planned",
      derivedSessionInvalidation: "planned",
      acceptsSessionCookies: false,
      storesRawSessionSecrets: false,
      returnsSessionSecretsInJson: false,
    },
    sessionStore: {
      status: "inactive",
      implementation: "in-memory-test-primitive",
      wiredIntoAuthorization: false,
      verifierMetadataPlanned: true,
      storesRawSessionSecrets: false,
      revocationRequired: true,
    },
    sessionVerifier: {
      status: "inactive",
      implementation: "hash-and-constant-time-compare-primitive",
      wiredIntoAuthorization: false,
      storesRawSessionSecrets: false,
    },
    csrf: {
      endpoint: "stubbed",
      tokenIssuance: "inactive",
      validation: "inactive",
      enforcement: "inactive",
      unsafeMethodsRequireCsrfWhenSessionAuthLive: true,
      bearerTokenRequiresBrowserCsrf: false,
      originRefererDefenseInDepth: true,
      storesRawTokens: false,
      logsRawTokens: false,
      tokenStore: {
        status: "inactive",
        implementation: "in-memory-test-primitive",
        wiredIntoAuthorization: false,
        wiredIntoRoutes: false,
      },
      tokenVerifier: {
        status: "inactive",
        implementation: "hash-and-constant-time-compare-primitive",
        wiredIntoAuthorization: false,
        wiredIntoRoutes: false,
        storesRawTokens: false,
      },
    },
    frontend: {
      tokenStorage: false,
      sessionSecretReadableByJs: false,
      loginUi: "inactive",
    },
    audit: {
      status: "planned",
      events: browserSessionAuditEvents,
      eventPrimitives: {
        status: "inactive",
        implementation: "in-memory-test-primitive",
        wiredIntoAuthorization: false,
        wiredIntoRoutes: false,
        sanitizesSecretMaterial: true,
      },
      excludesRawBearerTokens: true,
      excludesRawSessionSecrets: true,
      excludesRawPairingCodes: true,
      excludesRawCsrfTokens: true,
      excludesAuthorizationHeaders: true,
      excludesCookies: true,
      excludesVerifierHashes: true,
      excludesSalts: true,
      excludesUnsafeBrowserFingerprints: true,
    },
    readiness: {
      ready: false,
      blockers: browserSessionBlockers,
    },
  };
}
